### PR TITLE
Adds multilanguage support

### PR DESCRIPTION
**Pull request by charlyR**
Allows to easily add new languages in external json files, that the Translator singleton uses to return the text based on id.
Tries to load the specific language-region file, then the language, and falls back to english in case there is no location file.
Currently with the  "en","es" and "de" json files.
Wix, setup modified to distribute the language files with the installation.

### CODE REVIEW

**Comment by nilsbehlen** [comment]
Hi,
thanks a lot for your contribution!
If you are done with your work and want me to review it, just add me as reviewer.

**Comment by plettich** [comment]
It would be nice if the format of the translation file is supported by [weblate](https://docs.weblate.org/en/latest/formats.html).
That way we can crowd-source the translation and have one service for all our translations.

**Comment by nilsbehlen** [comment]
please remove `json.hpp` from this pr, thanks!

**Comment by nilsbehlen** [comment]
reviewer selection in on the upper right side

**Comment by charlyR** [comment]
I have modified .gitignore to exclude the external libraries, obj, bin, etc.

**Review by nilsbehlen — CHANGES_REQUESTED** [review]
i can do the changes myself

**Pull request merged**
